purchaseInvoiceType=com.example.demo.data.domain.PurchaseInvoiceType
movementType=com.example.demo.data.domain.BookStockMovementType
sourceType=com.example.demo.data.domain.BookStockMovementSourceType
