// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"database/sql"
)

type Book struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Author      sql.NullString `json:"author"`
	ReleaseDate string         `json:"release_date"`
	PublisherID int64          `json:"publisher_id"`
	GenreID     int64          `json:"genre_id"`
	Isbn        string         `json:"isbn"`
	CreateAt    string         `json:"create_at"`
	UpdateAt    string         `json:"update_at"`
	Version     int64          `json:"version"`
}

type BookGenre struct {
	ID        int64  `json:"id"`
	GenreName string `json:"genre_name"`
	CreateAt  string `json:"create_at"`
	UpdateAt  string `json:"update_at"`
	Version   int64  `json:"version"`
}

type BookSalesUnitPriceHistory struct {
	ID             int64          `json:"id"`
	BookID         int64          `json:"book_id"`
	SalesUnitPrice int64          `json:"sales_unit_price"`
	EffectiveFrom  string         `json:"effective_from"`
	EffectiveTo    sql.NullString `json:"effective_to"`
	CreateAt       string         `json:"create_at"`
	UpdateAt       string         `json:"update_at"`
	Version        int64          `json:"version"`
}

type BookStock struct {
	ID                int64  `json:"id"`
	BookStockStoreID  int64  `json:"book_stock_store_id"`
	BookStockBookID   int64  `json:"book_stock_book_id"`
	BookStockQuantity int64  `json:"book_stock_quantity"`
	CreateAt          string `json:"create_at"`
	UpdateAt          string `json:"update_at"`
	Version           int64  `json:"version"`
}

type BookStockMovement struct {
	ID             int64         `json:"id"`
	StoreID        int64         `json:"store_id"`
	BookID         int64         `json:"book_id"`
	MovementType   int64         `json:"movement_type"`
	QuantityDelta  int64         `json:"quantity_delta"`
	SourceType     sql.NullInt64 `json:"source_type"`
	SourceID       sql.NullInt64 `json:"source_id"`
	SourceDetailID sql.NullInt64 `json:"source_detail_id"`
	MovementDate   string        `json:"movement_date"`
	CreateAt       string        `json:"create_at"`
	UpdateAt       string        `json:"update_at"`
	Version        int64         `json:"version"`
}

type Publisher struct {
	ID            int64  `json:"id"`
	PublisherName string `json:"publisher_name"`
	CreateAt      string `json:"create_at"`
	UpdateAt      string `json:"update_at"`
	Version       int64  `json:"version"`
}

type PurchaseInvoice struct {
	ID                      int64         `json:"id"`
	PurchaseInvoiceType     int64         `json:"purchase_invoice_type"`
	ReturnPurchaseInvoiceID sql.NullInt64 `json:"return_purchase_invoice_id"`
	PurchaseInvoiceDate     string        `json:"purchase_invoice_date"`
	SupplierID              int64         `json:"supplier_id"`
	ReceivingStoreID        int64         `json:"receiving_store_id"`
	PurchaseInvoiceAmount   int64         `json:"purchase_invoice_amount"`
	CreateAt                string        `json:"create_at"`
	UpdateAt                string        `json:"update_at"`
	Version                 int64         `json:"version"`
}

type PurchaseInvoiceDetail struct {
	ID                             int64  `json:"id"`
	PurchaseInvoiceID              int64  `json:"purchase_invoice_id"`
	PurchaseInvoiceDetailBookID    int64  `json:"purchase_invoice_detail_book_id"`
	PurchaseInvoiceDetailUnitPrice int64  `json:"purchase_invoice_detail_unit_price"`
	PurchaseInvoiceDetailQuantity  int64  `json:"purchase_invoice_detail_quantity"`
	PurchaseInvoiceDetailAmount    int64  `json:"purchase_invoice_detail_amount"`
	CreateAt                       string `json:"create_at"`
	UpdateAt                       string `json:"update_at"`
	Version                        int64  `json:"version"`
}

type Store struct {
	ID        int64  `json:"id"`
	StoreName string `json:"store_name"`
	CreateAt  string `json:"create_at"`
	UpdateAt  string `json:"update_at"`
	Version   int64  `json:"version"`
}

type Supplier struct {
	ID           int64  `json:"id"`
	SupplierName string `json:"supplier_name"`
	CreateAt     string `json:"create_at"`
	UpdateAt     string `json:"update_at"`
	Version      int64  `json:"version"`
}
