// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"context"
)

type Querier interface {
	AddBookStockQuantity(ctx context.Context, arg AddBookStockQuantityParams) (int64, error)
	CountBookSearch(ctx context.Context, arg CountBookSearchParams) (int64, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (int64, error)
	CreateBookStock(ctx context.Context, arg CreateBookStockParams) (int64, error)
	CreateBookStockMovement(ctx context.Context, arg CreateBookStockMovementParams) (int64, error)
	CreatePurchaseInvoice(ctx context.Context, arg CreatePurchaseInvoiceParams) (int64, error)
	CreatePurchaseInvoiceDetail(ctx context.Context, arg CreatePurchaseInvoiceDetailParams) (int64, error)
	CreateSalesUnitPriceHistory(ctx context.Context, arg CreateSalesUnitPriceHistoryParams) (int64, error)
	DeleteBook(ctx context.Context, id int64) (int64, error)
	ExistsBookID(ctx context.Context, id int64) (bool, error)
	ExistsGenre(ctx context.Context, id int64) (bool, error)
	ExistsPublisher(ctx context.Context, id int64) (bool, error)
	ExistsStore(ctx context.Context, id int64) (bool, error)
	ExistsSupplier(ctx context.Context, id int64) (bool, error)
	FindBookByISBN(ctx context.Context, isbn string) (int64, error)
	GetBookBase(ctx context.Context, arg GetBookBaseParams) (GetBookBaseRow, error)
	GetBookStock(ctx context.Context, arg GetBookStockParams) (GetBookStockRow, error)
	GetNextSalesUnitPriceHistory(ctx context.Context, arg GetNextSalesUnitPriceHistoryParams) (GetNextSalesUnitPriceHistoryRow, error)
	GetPrevSalesUnitPriceHistory(ctx context.Context, arg GetPrevSalesUnitPriceHistoryParams) (GetPrevSalesUnitPriceHistoryRow, error)
	GetPurchaseInvoice(ctx context.Context, id int64) (GetPurchaseInvoiceRow, error)
	ListBookStocks(ctx context.Context, bookID int64) ([]ListBookStocksRow, error)
	ListPurchaseInvoiceDetails(ctx context.Context, purchaseInvoiceID int64) ([]ListPurchaseInvoiceDetailsRow, error)
	SearchBookBases(ctx context.Context, arg SearchBookBasesParams) ([]SearchBookBasesRow, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) (int64, error)
	UpdateSalesUnitPriceHistoryEffectiveTo(ctx context.Context, arg UpdateSalesUnitPriceHistoryEffectiveToParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
