// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const addBookStockQuantity = `-- name: AddBookStockQuantity :execrows
UPDATE book_stock
SET book_stock_quantity = book_stock_quantity + ?1,
    update_at = ?2,
    version = version + 1
WHERE id = ?3
`

type AddBookStockQuantityParams struct {
	QuantityDelta int64  `json:"quantity_delta"`
	Now           string `json:"now"`
	ID            int64  `json:"id"`
}

func (q *Queries) AddBookStockQuantity(ctx context.Context, arg AddBookStockQuantityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addBookStockQuantity, arg.QuantityDelta, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countBookSearch = `-- name: CountBookSearch :one
SELECT count(*)
FROM book b
JOIN book_sales_unit_price_history h
    ON h.book_id = b.id
   AND h.effective_from <= ?1
   AND (h.effective_to IS NULL OR ?1 <= h.effective_to)
WHERE
    (?2 = '' OR lower(b.title) LIKE lower(?2 || '%') OR lower(COALESCE(b.author, '')) LIKE lower(?2 || '%'))
    AND (?3 = '' OR (b.release_date >= ?3 AND b.release_date <= ?4))
`

type CountBookSearchParams struct {
	Today           string      `json:"today"`
	Keyword         interface{} `json:"keyword"`
	ReleaseDateFrom interface{} `json:"release_date_from"`
	ReleaseDateTo   string      `json:"release_date_to"`
}

func (q *Queries) CountBookSearch(ctx context.Context, arg CountBookSearchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBookSearch,
		arg.Today,
		arg.Keyword,
		arg.ReleaseDateFrom,
		arg.ReleaseDateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO book (title, author, release_date, publisher_id, genre_id, isbn, create_at, update_at, version)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?7, 1)
RETURNING id
`

type CreateBookParams struct {
	Title       string         `json:"title"`
	Author      sql.NullString `json:"author"`
	ReleaseDate string         `json:"release_date"`
	PublisherID int64          `json:"publisher_id"`
	GenreID     int64          `json:"genre_id"`
	Isbn        string         `json:"isbn"`
	Now         string         `json:"now"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.Title,
		arg.Author,
		arg.ReleaseDate,
		arg.PublisherID,
		arg.GenreID,
		arg.Isbn,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createBookStock = `-- name: CreateBookStock :one
INSERT INTO book_stock (book_stock_store_id, book_stock_book_id, book_stock_quantity, create_at, update_at, version)
VALUES (?1, ?2, ?3, ?4, ?4, 1)
RETURNING id
`

type CreateBookStockParams struct {
	StoreID  int64  `json:"store_id"`
	BookID   int64  `json:"book_id"`
	Quantity int64  `json:"quantity"`
	Now      string `json:"now"`
}

func (q *Queries) CreateBookStock(ctx context.Context, arg CreateBookStockParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createBookStock,
		arg.StoreID,
		arg.BookID,
		arg.Quantity,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createBookStockMovement = `-- name: CreateBookStockMovement :one
INSERT INTO book_stock_movement (store_id, book_id, movement_type, quantity_delta, source_type, source_id, source_detail_id, movement_date, create_at, update_at, version)
VALUES (?1, ?2, 2, ?3, 1, ?4, ?5, ?6, ?7, ?7, 1)
RETURNING id
`

type CreateBookStockMovementParams struct {
	StoreID        int64         `json:"store_id"`
	BookID         int64         `json:"book_id"`
	QuantityDelta  int64         `json:"quantity_delta"`
	SourceID       sql.NullInt64 `json:"source_id"`
	SourceDetailID sql.NullInt64 `json:"source_detail_id"`
	MovementDate   string        `json:"movement_date"`
	Now            string        `json:"now"`
}

func (q *Queries) CreateBookStockMovement(ctx context.Context, arg CreateBookStockMovementParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createBookStockMovement,
		arg.StoreID,
		arg.BookID,
		arg.QuantityDelta,
		arg.SourceID,
		arg.SourceDetailID,
		arg.MovementDate,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPurchaseInvoice = `-- name: CreatePurchaseInvoice :one
INSERT INTO purchase_invoice (purchase_invoice_type, return_purchase_invoice_id, purchase_invoice_date, supplier_id, receiving_store_id, purchase_invoice_amount, create_at, update_at, version)
VALUES (1, NULL, ?1, ?2, ?3, ?4, ?5, ?5, 1)
RETURNING id
`

type CreatePurchaseInvoiceParams struct {
	PurchaseInvoiceDate   string `json:"purchase_invoice_date"`
	SupplierID            int64  `json:"supplier_id"`
	ReceivingStoreID      int64  `json:"receiving_store_id"`
	PurchaseInvoiceAmount int64  `json:"purchase_invoice_amount"`
	Now                   string `json:"now"`
}

func (q *Queries) CreatePurchaseInvoice(ctx context.Context, arg CreatePurchaseInvoiceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPurchaseInvoice,
		arg.PurchaseInvoiceDate,
		arg.SupplierID,
		arg.ReceivingStoreID,
		arg.PurchaseInvoiceAmount,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPurchaseInvoiceDetail = `-- name: CreatePurchaseInvoiceDetail :one
INSERT INTO purchase_invoice_detail (purchase_invoice_id, purchase_invoice_detail_book_id, purchase_invoice_detail_unit_price, purchase_invoice_detail_quantity, purchase_invoice_detail_amount, create_at, update_at, version)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?6, 1)
RETURNING id
`

type CreatePurchaseInvoiceDetailParams struct {
	PurchaseInvoiceID int64  `json:"purchase_invoice_id"`
	BookID            int64  `json:"book_id"`
	UnitPrice         int64  `json:"unit_price"`
	Quantity          int64  `json:"quantity"`
	Amount            int64  `json:"amount"`
	Now               string `json:"now"`
}

func (q *Queries) CreatePurchaseInvoiceDetail(ctx context.Context, arg CreatePurchaseInvoiceDetailParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPurchaseInvoiceDetail,
		arg.PurchaseInvoiceID,
		arg.BookID,
		arg.UnitPrice,
		arg.Quantity,
		arg.Amount,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSalesUnitPriceHistory = `-- name: CreateSalesUnitPriceHistory :one
INSERT INTO book_sales_unit_price_history (book_id, sales_unit_price, effective_from, effective_to, create_at, update_at, version)
VALUES (?1, ?2, ?3, ?4, ?5, ?5, 1)
RETURNING id
`

type CreateSalesUnitPriceHistoryParams struct {
	BookID         int64          `json:"book_id"`
	SalesUnitPrice int64          `json:"sales_unit_price"`
	EffectiveFrom  string         `json:"effective_from"`
	EffectiveTo    sql.NullString `json:"effective_to"`
	Now            string         `json:"now"`
}

func (q *Queries) CreateSalesUnitPriceHistory(ctx context.Context, arg CreateSalesUnitPriceHistoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSalesUnitPriceHistory,
		arg.BookID,
		arg.SalesUnitPrice,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteBook = `-- name: DeleteBook :execrows
DELETE FROM book WHERE id = ?1
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBook, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const existsBookID = `-- name: ExistsBookID :one
SELECT EXISTS(SELECT 1 FROM book WHERE id = ?1)
`

func (q *Queries) ExistsBookID(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsBookID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsGenre = `-- name: ExistsGenre :one
SELECT EXISTS(SELECT 1 FROM book_genre WHERE id = ?1)
`

func (q *Queries) ExistsGenre(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsGenre, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsPublisher = `-- name: ExistsPublisher :one
SELECT EXISTS(SELECT 1 FROM publisher WHERE id = ?1)
`

func (q *Queries) ExistsPublisher(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsPublisher, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsStore = `-- name: ExistsStore :one
SELECT EXISTS(SELECT 1 FROM store WHERE id = ?1)
`

func (q *Queries) ExistsStore(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsStore, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsSupplier = `-- name: ExistsSupplier :one
SELECT EXISTS(SELECT 1 FROM supplier WHERE id = ?1)
`

func (q *Queries) ExistsSupplier(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsSupplier, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findBookByISBN = `-- name: FindBookByISBN :one
SELECT id FROM book WHERE isbn = ?1
`

func (q *Queries) FindBookByISBN(ctx context.Context, isbn string) (int64, error) {
	row := q.db.QueryRowContext(ctx, findBookByISBN, isbn)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getBookBase = `-- name: GetBookBase :one
SELECT
    b.id,
    b.title,
    b.author,
    b.release_date,
    b.publisher_id,
    p.publisher_name,
    b.genre_id,
    g.genre_name,
    b.isbn,
    h.sales_unit_price,
    b.update_at,
    b.version
FROM book b
JOIN publisher p ON p.id = b.publisher_id
JOIN book_genre g ON g.id = b.genre_id
JOIN book_sales_unit_price_history h
    ON h.book_id = b.id
   AND h.effective_from <= ?1
   AND (h.effective_to IS NULL OR ?1 <= h.effective_to)
WHERE b.id = ?2
`

type GetBookBaseParams struct {
	Today string `json:"today"`
	ID    int64  `json:"id"`
}

type GetBookBaseRow struct {
	ID             int64          `json:"id"`
	Title          string         `json:"title"`
	Author         sql.NullString `json:"author"`
	ReleaseDate    string         `json:"release_date"`
	PublisherID    int64          `json:"publisher_id"`
	PublisherName  string         `json:"publisher_name"`
	GenreID        int64          `json:"genre_id"`
	GenreName      string         `json:"genre_name"`
	Isbn           string         `json:"isbn"`
	SalesUnitPrice int64          `json:"sales_unit_price"`
	UpdateAt       string         `json:"update_at"`
	Version        int64          `json:"version"`
}

func (q *Queries) GetBookBase(ctx context.Context, arg GetBookBaseParams) (GetBookBaseRow, error) {
	row := q.db.QueryRowContext(ctx, getBookBase, arg.Today, arg.ID)
	var i GetBookBaseRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.ReleaseDate,
		&i.PublisherID,
		&i.PublisherName,
		&i.GenreID,
		&i.GenreName,
		&i.Isbn,
		&i.SalesUnitPrice,
		&i.UpdateAt,
		&i.Version,
	)
	return i, err
}

const getBookStock = `-- name: GetBookStock :one
SELECT id, book_stock_quantity, version
FROM book_stock
WHERE book_stock_store_id = ?1 AND book_stock_book_id = ?2
`

type GetBookStockParams struct {
	StoreID int64 `json:"store_id"`
	BookID  int64 `json:"book_id"`
}

type GetBookStockRow struct {
	ID                int64 `json:"id"`
	BookStockQuantity int64 `json:"book_stock_quantity"`
	Version           int64 `json:"version"`
}

func (q *Queries) GetBookStock(ctx context.Context, arg GetBookStockParams) (GetBookStockRow, error) {
	row := q.db.QueryRowContext(ctx, getBookStock, arg.StoreID, arg.BookID)
	var i GetBookStockRow
	err := row.Scan(&i.ID, &i.BookStockQuantity, &i.Version)
	return i, err
}

const getNextSalesUnitPriceHistory = `-- name: GetNextSalesUnitPriceHistory :one
SELECT id, effective_from
FROM book_sales_unit_price_history
WHERE book_id = ?1 AND effective_from >= ?2
ORDER BY effective_from ASC
LIMIT 1
`

type GetNextSalesUnitPriceHistoryParams struct {
	BookID        int64  `json:"book_id"`
	EffectiveFrom string `json:"effective_from"`
}

type GetNextSalesUnitPriceHistoryRow struct {
	ID            int64  `json:"id"`
	EffectiveFrom string `json:"effective_from"`
}

func (q *Queries) GetNextSalesUnitPriceHistory(ctx context.Context, arg GetNextSalesUnitPriceHistoryParams) (GetNextSalesUnitPriceHistoryRow, error) {
	row := q.db.QueryRowContext(ctx, getNextSalesUnitPriceHistory, arg.BookID, arg.EffectiveFrom)
	var i GetNextSalesUnitPriceHistoryRow
	err := row.Scan(&i.ID, &i.EffectiveFrom)
	return i, err
}

const getPrevSalesUnitPriceHistory = `-- name: GetPrevSalesUnitPriceHistory :one
SELECT id, effective_from
FROM book_sales_unit_price_history
WHERE book_id = ?1 AND effective_from < ?2
ORDER BY effective_from DESC
LIMIT 1
`

type GetPrevSalesUnitPriceHistoryParams struct {
	BookID        int64  `json:"book_id"`
	EffectiveFrom string `json:"effective_from"`
}

type GetPrevSalesUnitPriceHistoryRow struct {
	ID            int64  `json:"id"`
	EffectiveFrom string `json:"effective_from"`
}

func (q *Queries) GetPrevSalesUnitPriceHistory(ctx context.Context, arg GetPrevSalesUnitPriceHistoryParams) (GetPrevSalesUnitPriceHistoryRow, error) {
	row := q.db.QueryRowContext(ctx, getPrevSalesUnitPriceHistory, arg.BookID, arg.EffectiveFrom)
	var i GetPrevSalesUnitPriceHistoryRow
	err := row.Scan(&i.ID, &i.EffectiveFrom)
	return i, err
}

const getPurchaseInvoice = `-- name: GetPurchaseInvoice :one
SELECT id, purchase_invoice_type, return_purchase_invoice_id, purchase_invoice_date, supplier_id, receiving_store_id, purchase_invoice_amount, update_at, version
FROM purchase_invoice
WHERE id = ?1
`

type GetPurchaseInvoiceRow struct {
	ID                      int64         `json:"id"`
	PurchaseInvoiceType     int64         `json:"purchase_invoice_type"`
	ReturnPurchaseInvoiceID sql.NullInt64 `json:"return_purchase_invoice_id"`
	PurchaseInvoiceDate     string        `json:"purchase_invoice_date"`
	SupplierID              int64         `json:"supplier_id"`
	ReceivingStoreID        int64         `json:"receiving_store_id"`
	PurchaseInvoiceAmount   int64         `json:"purchase_invoice_amount"`
	UpdateAt                string        `json:"update_at"`
	Version                 int64         `json:"version"`
}

func (q *Queries) GetPurchaseInvoice(ctx context.Context, id int64) (GetPurchaseInvoiceRow, error) {
	row := q.db.QueryRowContext(ctx, getPurchaseInvoice, id)
	var i GetPurchaseInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.PurchaseInvoiceType,
		&i.ReturnPurchaseInvoiceID,
		&i.PurchaseInvoiceDate,
		&i.SupplierID,
		&i.ReceivingStoreID,
		&i.PurchaseInvoiceAmount,
		&i.UpdateAt,
		&i.Version,
	)
	return i, err
}

const listBookStocks = `-- name: ListBookStocks :many
SELECT
    bs.id,
    bs.book_stock_store_id,
    s.store_name,
    bs.book_stock_quantity
FROM book_stock bs
JOIN store s ON s.id = bs.book_stock_store_id
WHERE bs.book_stock_book_id = ?1
ORDER BY bs.book_stock_store_id, bs.id
`

type ListBookStocksRow struct {
	ID                int64  `json:"id"`
	BookStockStoreID  int64  `json:"book_stock_store_id"`
	StoreName         string `json:"store_name"`
	BookStockQuantity int64  `json:"book_stock_quantity"`
}

func (q *Queries) ListBookStocks(ctx context.Context, bookID int64) ([]ListBookStocksRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookStocks, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookStocksRow
	for rows.Next() {
		var i ListBookStocksRow
		if err := rows.Scan(
			&i.ID,
			&i.BookStockStoreID,
			&i.StoreName,
			&i.BookStockQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseInvoiceDetails = `-- name: ListPurchaseInvoiceDetails :many
SELECT id, purchase_invoice_id, purchase_invoice_detail_book_id, purchase_invoice_detail_unit_price, purchase_invoice_detail_quantity, purchase_invoice_detail_amount, update_at, version
FROM purchase_invoice_detail
WHERE purchase_invoice_id = ?1
ORDER BY id
`

type ListPurchaseInvoiceDetailsRow struct {
	ID                             int64  `json:"id"`
	PurchaseInvoiceID              int64  `json:"purchase_invoice_id"`
	PurchaseInvoiceDetailBookID    int64  `json:"purchase_invoice_detail_book_id"`
	PurchaseInvoiceDetailUnitPrice int64  `json:"purchase_invoice_detail_unit_price"`
	PurchaseInvoiceDetailQuantity  int64  `json:"purchase_invoice_detail_quantity"`
	PurchaseInvoiceDetailAmount    int64  `json:"purchase_invoice_detail_amount"`
	UpdateAt                       string `json:"update_at"`
	Version                        int64  `json:"version"`
}

func (q *Queries) ListPurchaseInvoiceDetails(ctx context.Context, purchaseInvoiceID int64) ([]ListPurchaseInvoiceDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPurchaseInvoiceDetails, purchaseInvoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurchaseInvoiceDetailsRow
	for rows.Next() {
		var i ListPurchaseInvoiceDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.PurchaseInvoiceID,
			&i.PurchaseInvoiceDetailBookID,
			&i.PurchaseInvoiceDetailUnitPrice,
			&i.PurchaseInvoiceDetailQuantity,
			&i.PurchaseInvoiceDetailAmount,
			&i.UpdateAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBookBases = `-- name: SearchBookBases :many
SELECT
    b.id,
    b.title,
    b.author,
    b.release_date,
    b.publisher_id,
    p.publisher_name,
    b.genre_id,
    g.genre_name,
    b.isbn,
    h.sales_unit_price,
    b.update_at,
    b.version
FROM book b
JOIN publisher p ON p.id = b.publisher_id
JOIN book_genre g ON g.id = b.genre_id
JOIN book_sales_unit_price_history h
    ON h.book_id = b.id
   AND h.effective_from <= ?1
   AND (h.effective_to IS NULL OR ?1 <= h.effective_to)
WHERE
    (?2 = '' OR lower(b.title) LIKE lower(?2 || '%') OR lower(COALESCE(b.author, '')) LIKE lower(?2 || '%'))
    AND (?3 = '' OR (b.release_date >= ?3 AND b.release_date <= ?4))
ORDER BY b.id
LIMIT ?6 OFFSET ?5
`

type SearchBookBasesParams struct {
	Today           string      `json:"today"`
	Keyword         interface{} `json:"keyword"`
	ReleaseDateFrom interface{} `json:"release_date_from"`
	ReleaseDateTo   string      `json:"release_date_to"`
	OffsetRows      int64       `json:"offset_rows"`
	LimitRows       int64       `json:"limit_rows"`
}

type SearchBookBasesRow struct {
	ID             int64          `json:"id"`
	Title          string         `json:"title"`
	Author         sql.NullString `json:"author"`
	ReleaseDate    string         `json:"release_date"`
	PublisherID    int64          `json:"publisher_id"`
	PublisherName  string         `json:"publisher_name"`
	GenreID        int64          `json:"genre_id"`
	GenreName      string         `json:"genre_name"`
	Isbn           string         `json:"isbn"`
	SalesUnitPrice int64          `json:"sales_unit_price"`
	UpdateAt       string         `json:"update_at"`
	Version        int64          `json:"version"`
}

func (q *Queries) SearchBookBases(ctx context.Context, arg SearchBookBasesParams) ([]SearchBookBasesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchBookBases,
		arg.Today,
		arg.Keyword,
		arg.ReleaseDateFrom,
		arg.ReleaseDateTo,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBookBasesRow
	for rows.Next() {
		var i SearchBookBasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.ReleaseDate,
			&i.PublisherID,
			&i.PublisherName,
			&i.GenreID,
			&i.GenreName,
			&i.Isbn,
			&i.SalesUnitPrice,
			&i.UpdateAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :execrows
UPDATE book
SET title = ?1,
    author = ?2,
    release_date = ?3,
    publisher_id = ?4,
    genre_id = ?5,
    isbn = ?6,
    update_at = ?7,
    version = version + 1
WHERE id = ?8 AND version = ?9
`

type UpdateBookParams struct {
	Title       string         `json:"title"`
	Author      sql.NullString `json:"author"`
	ReleaseDate string         `json:"release_date"`
	PublisherID int64          `json:"publisher_id"`
	GenreID     int64          `json:"genre_id"`
	Isbn        string         `json:"isbn"`
	Now         string         `json:"now"`
	ID          int64          `json:"id"`
	Version     int64          `json:"version"`
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateBook,
		arg.Title,
		arg.Author,
		arg.ReleaseDate,
		arg.PublisherID,
		arg.GenreID,
		arg.Isbn,
		arg.Now,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSalesUnitPriceHistoryEffectiveTo = `-- name: UpdateSalesUnitPriceHistoryEffectiveTo :execrows
UPDATE book_sales_unit_price_history
SET effective_to = ?1, update_at = ?2, version = version + 1
WHERE id = ?3
`

type UpdateSalesUnitPriceHistoryEffectiveToParams struct {
	EffectiveTo sql.NullString `json:"effective_to"`
	Now         string         `json:"now"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateSalesUnitPriceHistoryEffectiveTo(ctx context.Context, arg UpdateSalesUnitPriceHistoryEffectiveToParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSalesUnitPriceHistoryEffectiveTo, arg.EffectiveTo, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
