package com.example.demo.mybatis.generator.entity;

import java.util.Date;

public class BookEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbg.generated Wed Jun 03 00:14:18 JST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.title
     *
     * @mbg.generated Wed Jun 03 00:14:18 JST 2026
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbg.generated Wed Jun 03 00:14:18 JST 2026
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.create_at
     *
     * @mbg.generated Wed Jun 03 00:14:18 JST 2026
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.update_at
     *
     * @mbg.generated Wed Jun 03 00:14:18 JST 2026
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.version
     *
     * @mbg.generated Wed Jun 03 00:14:18 JST 2026
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbg.generated Wed Jun 03 00:14:18 JST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbg.generated Wed Jun 03 00:14:18 JST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.title
     *
     * @return the value of book.title
     *
     * @mbg.generated Wed Jun 03 00:14:18 JST 2026
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.title
     *
     * @param title the value for book.title
     *
     * @mbg.generated Wed Jun 03 00:14:18 JST 2026
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author
     *
     * @return the value of book.author
     *
     * @mbg.generated Wed Jun 03 00:14:18 JST 2026
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author
     *
     * @param author the value for book.author
     *
     * @mbg.generated Wed Jun 03 00:14:18 JST 2026
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.create_at
     *
     * @return the value of book.create_at
     *
     * @mbg.generated Wed Jun 03 00:14:18 JST 2026
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.create_at
     *
     * @param createAt the value for book.create_at
     *
     * @mbg.generated Wed Jun 03 00:14:18 JST 2026
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.update_at
     *
     * @return the value of book.update_at
     *
     * @mbg.generated Wed Jun 03 00:14:18 JST 2026
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.update_at
     *
     * @param updateAt the value for book.update_at
     *
     * @mbg.generated Wed Jun 03 00:14:18 JST 2026
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.version
     *
     * @return the value of book.version
     *
     * @mbg.generated Wed Jun 03 00:14:18 JST 2026
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.version
     *
     * @param version the value for book.version
     *
     * @mbg.generated Wed Jun 03 00:14:18 JST 2026
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}