DROP TABLE IF EXISTS book_stock_movement;
DROP TABLE IF EXISTS book_stock;
DROP TABLE IF EXISTS book_sales_unit_price_history;
DROP TABLE IF EXISTS purchase_invoice_detail;
DROP TABLE IF EXISTS purchase_invoice;
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS book_genre;
DROP TABLE IF EXISTS publisher;
DROP TABLE IF EXISTS store;
DROP TABLE IF EXISTS supplier;

CREATE TABLE publisher (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_name VARCHAR(100) NOT NULL,
    create_at TIMESTAMP NOT NULL,
    update_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL
);

comment on table publisher is '出版社';
comment on column publisher.publisher_name is '出版社名';
comment on column publisher.create_at is '作成日時';
comment on column publisher.update_at is '更新日時';
comment on column publisher.version is 'バージョン';

CREATE TABLE book_genre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(100) NOT NULL,
    create_at TIMESTAMP NOT NULL,
    update_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL
);

comment on table book_genre is '本ジャンル';
comment on column book_genre.genre_name is 'ジャンル名';
comment on column book_genre.create_at is '作成日時';
comment on column book_genre.update_at is '更新日時';
comment on column book_genre.version is 'バージョン';

CREATE TABLE book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    author VARCHAR(200),
    release_date DATE NOT NULL,
    publisher_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    isbn VARCHAR(13) NOT NULL,
    create_at TIMESTAMP NOT NULL,
    update_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL,
    FOREIGN KEY (publisher_id) REFERENCES publisher(id),
    FOREIGN KEY (genre_id) REFERENCES book_genre(id)
);

CREATE INDEX idx_book_01 ON book(release_date);
CREATE INDEX idx_book_02 ON book(publisher_id);
CREATE INDEX idx_book_03 ON book(genre_id);
CREATE INDEX idx_book_04 ON book(title);
CREATE INDEX idx_book_05 ON book(author);

ALTER TABLE book ADD CONSTRAINT unq_book_01 UNIQUE (isbn);

comment on table book is '本';
comment on column book.author is '著者';
comment on column book.release_date is '発売日付';
comment on column book.create_at is '作成日時';
comment on column book.title is 'タイトル';
comment on column book.publisher_id is '出版社ID';
comment on column book.genre_id is 'ジャンルID';
comment on column book.isbn is 'ISBN';
comment on column book.update_at is '更新日時';
comment on column book.version is 'バージョン';

CREATE TABLE supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR(100) NOT NULL,
    create_at TIMESTAMP NOT NULL,
    update_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL
);

comment on table supplier is '仕入先';
comment on column supplier.supplier_name is '仕入先名';
comment on column supplier.create_at is '作成日時';
comment on column supplier.update_at is '更新日時';
comment on column supplier.version is 'バージョン';

CREATE TABLE store (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name VARCHAR(100) NOT NULL,
    create_at TIMESTAMP NOT NULL,
    update_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL
);

comment on table store is '店舗';
comment on column store.store_name is '店舗名';
comment on column store.create_at is '作成日時';
comment on column store.update_at is '更新日時';
comment on column store.version is 'バージョン';

CREATE TABLE purchase_invoice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_invoice_type INTEGER NOT NULL,
    return_purchase_invoice_id BIGINT,
    purchase_invoice_date DATE NOT NULL,
    supplier_id BIGINT NOT NULL,
    receiving_store_id BIGINT NOT NULL,
    purchase_invoice_amount BIGINT NOT NULL,
    create_at TIMESTAMP NOT NULL,
    update_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT check_purchase_invoice_type CHECK (purchase_invoice_type IN (1, 2)),
    FOREIGN KEY (return_purchase_invoice_id) REFERENCES purchase_invoice(id),
    FOREIGN KEY (supplier_id) REFERENCES supplier(id),
    FOREIGN KEY (receiving_store_id) REFERENCES store(id)
);

CREATE INDEX idx_purchase_invoice_01 ON purchase_invoice(purchase_invoice_type);
CREATE INDEX idx_purchase_invoice_02 ON purchase_invoice(return_purchase_invoice_id);
CREATE INDEX idx_purchase_invoice_03 ON purchase_invoice(purchase_invoice_date);
CREATE INDEX idx_purchase_invoice_04 ON purchase_invoice(supplier_id);
CREATE INDEX idx_purchase_invoice_05 ON purchase_invoice(receiving_store_id);

comment on table purchase_invoice is '仕入伝票';
comment on column purchase_invoice.purchase_invoice_type is '仕入伝票種別';
comment on column purchase_invoice.return_purchase_invoice_id is '返品元仕入伝票ID';
comment on column purchase_invoice.purchase_invoice_date is '仕入伝票日付';
comment on column purchase_invoice.supplier_id is '仕入先ID';
comment on column purchase_invoice.receiving_store_id is '入庫店舗ID';
comment on column purchase_invoice.purchase_invoice_amount is '仕入伝票金額';
comment on column purchase_invoice.create_at is '作成日時';
comment on column purchase_invoice.update_at is '更新日時';
comment on column purchase_invoice.version is 'バージョン';

CREATE TABLE purchase_invoice_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_invoice_id BIGINT NOT NULL,
    purchase_invoice_detail_book_id BIGINT NOT NULL,
    purchase_invoice_detail_unit_price INTEGER NOT NULL,
    purchase_invoice_detail_quantity INTEGER NOT NULL,
    purchase_invoice_detail_amount BIGINT NOT NULL,
    create_at TIMESTAMP NOT NULL,
    update_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL,
    FOREIGN KEY (purchase_invoice_id) REFERENCES purchase_invoice(id),
    FOREIGN KEY (purchase_invoice_detail_book_id) REFERENCES book(id)
);

CREATE INDEX idx_purchase_invoice_detail_01 ON purchase_invoice_detail(purchase_invoice_id);
CREATE INDEX idx_purchase_invoice_detail_02 ON purchase_invoice_detail(purchase_invoice_detail_book_id);

comment on table purchase_invoice_detail is '仕入伝票明細';
comment on column purchase_invoice_detail.purchase_invoice_id is '仕入伝票ID';
comment on column purchase_invoice_detail.purchase_invoice_detail_book_id is '仕入伝票明細本ID';
comment on column purchase_invoice_detail.purchase_invoice_detail_unit_price is '仕入伝票明細単価';
comment on column purchase_invoice_detail.purchase_invoice_detail_quantity is '仕入伝票明細数量';
comment on column purchase_invoice_detail.purchase_invoice_detail_amount is '仕入伝票明細金額';
comment on column purchase_invoice_detail.create_at is '作成日時';
comment on column purchase_invoice_detail.update_at is '更新日時';
comment on column purchase_invoice_detail.version is 'バージョン';

CREATE TABLE book_sales_unit_price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    sales_unit_price INTEGER NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    create_at TIMESTAMP NOT NULL,
    update_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT check_book_sales_unit_price_history_01 CHECK (sales_unit_price BETWEEN 1 AND 10000),
    CONSTRAINT check_book_sales_unit_price_history_02 CHECK (effective_to IS NULL OR effective_from <= effective_to),
    FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE CASCADE
);

CREATE INDEX idx_book_sales_unit_price_history_01 ON book_sales_unit_price_history(book_id);
CREATE INDEX idx_book_sales_unit_price_history_02 ON book_sales_unit_price_history(effective_from);
CREATE INDEX idx_book_sales_unit_price_history_03 ON book_sales_unit_price_history(effective_to);

ALTER TABLE book_sales_unit_price_history ADD CONSTRAINT unq_book_sales_unit_price_history_01 UNIQUE (book_id, effective_from);

comment on table book_sales_unit_price_history is '本販売単価履歴';
comment on column book_sales_unit_price_history.book_id is '本ID';
comment on column book_sales_unit_price_history.sales_unit_price is '販売単価';
comment on column book_sales_unit_price_history.effective_from is '有効開始日';
comment on column book_sales_unit_price_history.effective_to is '有効終了日';
comment on column book_sales_unit_price_history.create_at is '作成日時';
comment on column book_sales_unit_price_history.update_at is '更新日時';
comment on column book_sales_unit_price_history.version is 'バージョン';

CREATE TABLE book_stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_stock_store_id BIGINT NOT NULL,
    book_stock_book_id BIGINT NOT NULL,
    book_stock_quantity INTEGER NOT NULL,
    create_at TIMESTAMP NOT NULL,
    update_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL,
    FOREIGN KEY (book_stock_store_id) REFERENCES store(id),
    FOREIGN KEY (book_stock_book_id) REFERENCES book(id)
);

CREATE INDEX idx_book_stock_01 ON book_stock(book_stock_store_id);
CREATE INDEX idx_book_stock_02 ON book_stock(book_stock_book_id);
CREATE INDEX idx_book_stock_03 ON book_stock(book_stock_store_id, book_stock_book_id);

ALTER TABLE book_stock ADD CONSTRAINT unq_book_stock_01 UNIQUE (book_stock_store_id, book_stock_book_id);

comment on table book_stock is '本在庫';
comment on column book_stock.book_stock_store_id is '本在庫店舗ID';
comment on column book_stock.book_stock_book_id is '本在庫本ID';
comment on column book_stock.book_stock_quantity is '本在庫数量';
comment on column book_stock.create_at is '作成日時';
comment on column book_stock.update_at is '更新日時';
comment on column book_stock.version is 'バージョン';

CREATE TABLE book_stock_movement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    movement_type INTEGER NOT NULL,
    quantity_delta INTEGER NOT NULL,
    source_type INTEGER,
    source_id BIGINT,
    source_detail_id BIGINT,
    movement_date DATE NOT NULL,
    create_at TIMESTAMP NOT NULL,
    update_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT check_book_stock_movement_type CHECK (movement_type IN (1, 2, 3, 4, 5, 6, 7, 8)),
    CONSTRAINT check_book_stock_movement_source_type CHECK (source_type IS NULL OR source_type IN (1, 2, 3, 4)),
    CONSTRAINT fk_book_stock_movement_01 FOREIGN KEY (store_id) REFERENCES store(id) ON DELETE CASCADE,
    CONSTRAINT fk_book_stock_movement_02 FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE CASCADE
);

CREATE INDEX idx_book_stock_movement_01 ON book_stock_movement(store_id, book_id);
CREATE INDEX idx_book_stock_movement_02 ON book_stock_movement(movement_date);
CREATE INDEX idx_book_stock_movement_03 ON book_stock_movement(movement_type);

comment on table book_stock_movement is '本在庫増減履歴';
comment on column book_stock_movement.store_id is '店舗ID';
comment on column book_stock_movement.book_id is '本ID';
comment on column book_stock_movement.movement_type is '在庫増減種別';
comment on column book_stock_movement.quantity_delta is '増減数量';
comment on column book_stock_movement.source_type is '発生元種別';
comment on column book_stock_movement.source_id is '発生元ID';
comment on column book_stock_movement.source_detail_id is '発生元明細ID';
comment on column book_stock_movement.movement_date is '在庫増減日付';
comment on column book_stock_movement.create_at is '作成日時';
comment on column book_stock_movement.update_at is '更新日時';
comment on column book_stock_movement.version is 'バージョン';
