package com.example.demo.mybatis.generator.mapper;

import com.example.demo.mybatis.generator.entity.BookEntity;
import com.example.demo.mybatis.generator.entity.BookEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Jun 06 18:58:35 JST 2026
     */
    long countByExample(BookEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Jun 06 18:58:35 JST 2026
     */
    int deleteByExample(BookEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Jun 06 18:58:35 JST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Jun 06 18:58:35 JST 2026
     */
    int insert(BookEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Jun 06 18:58:35 JST 2026
     */
    int insertSelective(BookEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Jun 06 18:58:35 JST 2026
     */
    List<BookEntity> selectByExample(BookEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Jun 06 18:58:35 JST 2026
     */
    BookEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Jun 06 18:58:35 JST 2026
     */
    int updateByExampleSelective(@Param("row") BookEntity row, @Param("example") BookEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Jun 06 18:58:35 JST 2026
     */
    int updateByExample(@Param("row") BookEntity row, @Param("example") BookEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Jun 06 18:58:35 JST 2026
     */
    int updateByPrimaryKeySelective(BookEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Jun 06 18:58:35 JST 2026
     */
    int updateByPrimaryKey(BookEntity row);
}