DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS publisher;

CREATE TABLE publisher (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_name VARCHAR(100) NOT NULL,
    create_at TIMESTAMP NOT NULL,
    update_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL
);

comment on table publisher is '出版社';
comment on column publisher.publisher_name is '出版社名';
comment on column publisher.create_at is '作成日時';
comment on column publisher.update_at is '更新日時';
comment on column publisher.version is 'バージョン';

CREATE TABLE book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    author VARCHAR(200),
    release_date DATE NOT NULL,
    publisher_id BIGINT NOT NULL,
    create_at TIMESTAMP NOT NULL,
    update_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL,
    FOREIGN KEY (publisher_id) REFERENCES publisher(id)
);

CREATE INDEX idx_book_01 ON book(release_date);
CREATE INDEX idx_book_02 ON book(publisher_id);

comment on table book is '本';
comment on column book.author is '著者';
comment on column book.release_date is '発売日付';
comment on column book.create_at is '作成日時';
comment on column book.title is 'タイトル';
comment on column book.publisher_id is '出版社ID';
comment on column book.update_at is '更新日時';
comment on column book.version is 'バージョン';
