DROP TABLE IF EXISTS book;

CREATE TABLE book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    author VARCHAR(200),
    release_date DATE NOT NULL,
    create_at TIMESTAMP NOT NULL,
    update_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL
);

CREATE INDEX idx_book_01 ON book(release_date);

comment on table book is '本';
comment on column book.author is '著者';
comment on column book.release_date is '発売日付';
comment on column book.create_at is '作成日時';
comment on column book.title is 'タイトル';
comment on column book.update_at is '更新日時';
comment on column book.version is 'バージョン';
