server:
  port: ${PORTAL_SERVER_PORT:8081}

app:
  keycloak:
    client-id: springboot-portal
    issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/sample-realm}

spring:
  application:
    name: portal
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${PORTAL_CLIENT_ID:springboot-portal}
            client-secret: ${PORTAL_CLIENT_SECRET:portal-client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          keycloak:
            authorization-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/sample-realm}/protocol/openid-connect/auth
            token-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/sample-realm}/protocol/openid-connect/token
            user-info-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/sample-realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/sample-realm}/protocol/openid-connect/certs
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/sample-realm}
