CREATE TABLE IF NOT EXISTS orders (
  id BIGINT NOT NULL,
  order_number VARCHAR(32) NOT NULL,
  customer_name VARCHAR(100) NOT NULL,
  product_name VARCHAR(100) NOT NULL,
  amount DECIMAL(15,2) NOT NULL,
  status VARCHAR(20) NOT NULL,
  ordered_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (order_number)
);

CREATE INDEX IF NOT EXISTS idx_orders_ordered_id ON orders (ordered_at, id);
CREATE INDEX IF NOT EXISTS idx_orders_status_ordered_id ON orders (status, ordered_at, id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders (created_at);

CREATE TABLE IF NOT EXISTS csv_export_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_username VARCHAR(100) NOT NULL,
  status VARCHAR(20) NOT NULL,
  filter_json VARCHAR(4000) NOT NULL,
  snapshot_at TIMESTAMP NULL,
  file_path VARCHAR(500) NULL,
  record_count BIGINT NOT NULL DEFAULT 0,
  error_message VARCHAR(1000) NULL,
  created_at TIMESTAMP NOT NULL,
  started_at TIMESTAMP NULL,
  completed_at TIMESTAMP NULL,
  expires_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS idx_export_jobs_dispatch ON csv_export_jobs (status, created_at);
CREATE INDEX IF NOT EXISTS idx_export_jobs_owner ON csv_export_jobs (owner_username, created_at);
CREATE INDEX IF NOT EXISTS idx_export_jobs_expiry ON csv_export_jobs (expires_at);
